{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1" }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: topologies.netclab.io
spec:
  group: netclab.io
  scope: Namespaced
  names:
    plural: topologies
    singular: topology
    kind: Topology
    shortNames:
      - topo
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                nodes:
                  type: array
                  items:
                    type: object
                    required: [name, template]
                    properties:
                      name:
                        type: string
                      template:
                        type: string
                      interfaces:
                        type: array
                        items:
                          type: object
                          required: [name, network]
                          properties:
                            name:
                              type: string
                            network:
                              type: string
                networks:
                  type: array
                  items:
                    type: object
                    required: [name, type]
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                        enum: ["bridge", "pod2pod"]
                      parameters:
                        type: object
                        additionalProperties: true
{{- end }}
