apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cni1
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "cni1",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "cni1",
          "isGateway": true,
          "isDefaultGateway": false,
          "ipam": {
            "type": "host-local",
            "ranges": [
              [
                {
                  "subnet": "10.10.0.0/24",
                  "gateway": "10.10.0.254"
                }
              ]
            ],
            "routes": [
              { "dst": "10.0.0.0/8" },
              { "dst": "172.16.0.0/12" },
              { "dst": "192.168.0.0/16" }
            ]
          }
        }
      ]
    }'
