apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cni2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "cni2",
      "plugins": [
        {
          "type": "bridge", "isGateway": true, "isDefaultGateway": true,
          "bridge": "cni2",
          "ipam": { "type": "host-local", "subnet": "100.65.1.0/24" }
        }
      ]
    }'

