apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cni3
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "cni3",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "cni3",
          "ipam": {}
        }
      ]
    }'

