apiVersion: v1
kind: Pod
metadata:
  name: p1
  annotations:
    k8s.v1.cni.cncf.io/networks: cni2, cni3
spec:
  containers:
  - name: p1
    command: ["/bin/sh", "-c", "sleep inf"]
    image: ubuntu:latest

