apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cni2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "cni2",
      "plugins": [
        {
          "name": "cni2",
          "type": "ptp",
          "ipam": {}
        }
      ]
    }'
