apiVersion: v1
kind: Pod
metadata:
  name: otg-port-2
  annotations:
    k8s.v1.cni.cncf.io/networks: cni1@veth2
  labels:
    app: ixia-c
    role: port-2
spec:
  containers:
    - name: traffic-engine-2
      image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:latest
      env:
        - name: ARG_IFACE_LIST
          value: virtual@af_packet,veth2
        - name: OPT_NO_HUGEPAGES
          value: "Yes"
        - name: OPT_ADAPTIVE_CPU_USAGE
          value: "Yes"
        - name: OPT_LISTEN_PORT
          value: "5555"
        - name: ARG_CORE_LIST
          value: 1 1 1
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 500m
          memory: 250Mi
    - name: protocol-engine-2
      image: ghcr.io/open-traffic-generator/ixia-c-protocol-engine:latest
      env:
        - name: INTF_LIST
          value: veth2
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
  restartPolicy: Always
