#!/bin/bash

set -e


log() {
  local filename="$(echo $0 | awk -F'/' '{printf $NF}')"
  echo "$(date -Is -u) $filename $*" >> $cnilog
}


cnilog="/var/log/cni.log"
input=$(cat /dev/stdin)
netns="$(echo $CNI_NETNS | awk -F'/' '{printf $NF}')"


log "$CNI_COMMAND $cniconfig"


case $CNI_COMMAND in
ADD)
  {
    flock 9
    ip link add p1 type veth peer name p2 || true
    ip link set p1 netns "$netns" || ip link set p2 netns "$netns"
    ip netns exec "$netns" ip link set p1 name "$CNI_IFNAME" || ip netns exec "$netns" ip link set p2 name "$CNI_IFNAME"
    ip netns exec "$netns" ip link set up name "$CNI_IFNAME"
  } 9>/tmp/cni-pod2pod.lock

  output_template='
	{
	  "cniVersion": "%s",
	  "interfaces": [
	      {
	          "name": "%s",
	          "sandbox": "%s"
	      }
	  ]
	}'

  cniVersion=$(echo $input | jq -r ".cniVersion")

  output=$(printf "$output_template" "$cniVersion" "$CNI_IFNAME" "$netns")
  echo "$output"
;;
DEL)
  ip netns exec "$netns" ip link del "$CNI_IFNAME" || true
;;
*)
  exit 1
;;
esac
