#!/bin/bash

set -e


DEBUG=false

log() {
  if ${DEBUG}; then
    cnilog="/var/log/cni.log"
    echo "$(date -Is -u) $*" >> $cnilog
  fi
}


netns="$(echo $CNI_NETNS | awk -F'/' '{printf $NF}')"


case $CNI_COMMAND in

ADD)
  input=$(cat /dev/stdin)
  cniVersion=$(echo $input | jq -r '.cniVersion')
  netName=$(echo $input | jq -r '.name')

  {
    flock 9
    p1="${netName}-p1"
    p2="${netName}-p2"

    log "$CNI_COMMAND $CNI_ARGS"

    ip link add ${p1} type veth peer name ${p2} || true
    ip link set ${p1} netns "$netns" || ip link set ${p2} netns "$netns"
    ip netns exec "$netns" ip link set ${p1} name "$CNI_IFNAME" || ip netns exec "$netns" ip link set ${p2} name "$CNI_IFNAME"
    ip netns exec "$netns" ip link set up name "$CNI_IFNAME"
  } 9>/tmp/cni-pod2pod.lock

  output_template='
	{
	  "cniVersion": "%s",
	  "interfaces": [
	      {
	          "name": "%s",
	          "sandbox": "%s"
	      }
	  ]
	}'

  output=$(printf "$output_template" "$cniVersion" "$CNI_IFNAME" "$netns")
  echo "$output"
;;

DEL)
  log "$CNI_COMMAND $CNI_ARGS"
  ip netns exec "$netns" ip link del "$CNI_IFNAME" || true
;;

*)
  exit 1
;;
esac
