#!/bin/bash

set -e


DEBUG="false"

(! eval $DEBUG ) || cnilog="/var/log/cni.log"
(! eval $DEBUG ) || log() { echo "$(date -Is -u) $*" >> $cnilog; }

input=$(cat /dev/stdin)
cniVersion=$(echo $input | awk -F ',' '{ for (i=1; i<=NF; i++) { if($i ~ /"cniVersion":/) printf $i } }' | awk -F':' '{printf $2}' | tr -d '"{}')
netName=$(echo $input | awk -F ',' '{ for (i=1; i<=NF; i++) { if($i ~ /"name":/) printf $i } }' | awk -F':' '{printf $2}' | tr -d '"{}')
netns="$(echo $CNI_NETNS | awk -F'/' '{printf $NF}')"


case $CNI_COMMAND in

ADD)
  {
    flock 9

    p1="${netName}-p1"
    p2="${netName}-p2"

    (! eval $DEBUG ) || log "$CNI_COMMAND $CNI_ARGS"

    ip link add ${p1} type veth peer name ${p2} || true
    ip link set ${p1} netns "$netns" || ip link set ${p2} netns "$netns"
    ip netns exec "$netns" ip link set ${p1} name "$CNI_IFNAME" || ip netns exec "$netns" ip link set ${p2} name "$CNI_IFNAME"
    ip netns exec "$netns" ip link set up name "$CNI_IFNAME"
  } 9>/tmp/cni-pod2pod.lock

  output_template='
	{
	  "cniVersion": "%s",
	  "interfaces": [
	      {
	          "name": "%s",
	          "sandbox": "%s"
	      }
	  ]
	}'

  output=$(printf "$output_template" "$cniVersion" "$CNI_IFNAME" "$netns")
  echo "$output"
;;

DEL)
  (! eval $DEBUG ) || log "$CNI_COMMAND $CNI_ARGS"
  ip netns exec "$netns" ip link del "$CNI_IFNAME" || true
;;

*)
  exit 1
;;
esac
