apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: sr01
  labels:
    kubevirt.io/os: srlinux
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: sr01
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          interfaces:
          - name: default
            bridge: {}
          # - name: ge2
          #   bridge: {}
          disks:
          - disk:
              bus: virtio
            name: disk0
        resources:
          requests:
            memory: 4Gi
      volumes:
      - name: disk0
        containerDisk:
          image: ghcr.io/nokia/srlinux:24.10.1
      networks:
      - name: default
        pod: {}
      # - name: ge2
      #   multus:
      #     networkName: cni1
