{{- $ns := .Values.topology.namespace | default "default" }}

{{- range .Values.topology.networks }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .name }}
  namespace: {{ $ns }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "{{ .name }}"
      "plugins": [
        {
          "type": "bridge",
          "bridge": "{{ .name }}",
          "ipam": {}
        }
      ]
    }'
{{- end }}

{{- range .Values.topology.nodes }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  namespace: {{ $ns }}
data:
  hw.yaml: |
{{ .config | indent 4 }}

---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
  namespace: {{ $ns }}
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      {{- range .interfaces }}
      - name: {{ .network }}
      {{- end }}
spec:
  containers:
    - name: {{ .name }}
      image: ghcr.io/nokia/srlinux
      command:
        - bash
        - -c
        - /entrypoint.sh
      volumeMounts:
        - name: config
          mountPath: /etc/srlinux
  volumes:
    - name: config
      configMap:
        name: {{ .name }}-config
{{- end }}
