apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: b0
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "b0",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "b0",
          "isGateway": true,
          "isDefaultGateway": false,
          "ipam": {
            "type": "host-local",
            "ranges": [
              [
                {
                  "subnet": "10.0.0.0/24",
                  "gateway": "10.0.0.254"
                }
              ]
            ],
            "routes": [
              { "dst": "10.0.0.0/8" },
              { "dst": "172.16.0.0/12" },
              { "dst": "192.168.0.0/16" }
            ]
          }
        }
      ]
    }'

{{- $ns := .Values.topology.namespace | default "default" }}

{{- range .Values.topology.networks }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .name }}
  namespace: {{ $ns }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "{{ .name }}"
      "plugins": [
        {
          "type": "bridge",
          "bridge": "{{ .name }}",
          "ipam": {}
        }
      ]
    }'
{{- end }}

{{- range .Values.topology.nodes }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  namespace: {{ $ns }}
data:
  hw.yaml: |
{{ .config | indent 4 }}

---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
  namespace: {{ $ns }}
  annotations:
    v1.multus-cni.io/default-network: b0
    k8s.v1.cni.cncf.io/networks: {{- $nets := list -}}{{- range $index, $int := .interfaces -}}{{- $nets = append $nets (printf "%s@e1-%d" $int.network (add $index 1)) -}}{{- end }} {{ join "," $nets }}
spec:
  containers:
    - name: {{ .name }}
      image: ghcr.io/nokia/srlinux
      command:
        - bash
        - -c
        - /entrypoint.sh
      volumeMounts:
        - name: config
          mountPath: /etc/srlinux
  volumes:
    - name: config
      configMap:
        name: {{ .name }}-config
{{- end }}
