apiVersion: v1
kind: Pod
metadata:
  name: pod1
  annotations:
    v1.multus-cni.io/default-network: cni1
    k8s.v1.cni.cncf.io/networks: cni2@eth1
spec:
  containers:
  - args:
    - sh
    - -c
    - sleep inf
    image: alpine:latest
    name: pod1
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
