apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cni1
spec:
  config: '{
      "cniVersion": "0.4.0",
      "name": "cni1",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "cni1",
          "ipam": {}
        }
      ]
    }'
