apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cni2
spec:
  config: '{
      "cniVersion": "0.4.0",
      "name": "cni2",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "cni2",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.1.0/24"
          }
        },
        {
          "type": "accept-bridge",
          "name": "cni2"
        }
      ]
    }'
