name: deploy and test

on:
  workflow_dispatch: {}
  push:
    tags:
    - v*

jobs:
  install:
    runs-on: ubuntu-latest

    steps:

    - name: Install kubectl
      run: |
        [ $(uname -m) = x86_64 ] && export os="linux/amd64"
        [ $(uname -m) = aarch64 ] && export os="darwin/arm64"
        curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/$os/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Install kind
      run: |
        [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64
        [ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-arm64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install vLab
      run: ./vlab_install.sh nokubevirt

    # - name: Install bats
    #   run: sudo apt-get -y install bats

    # - name: Run tests
    #   run: |
    #     export TERM=dumb
    #     export ROUTERS=("srl01" "srl02")
    #     for router in ${ROUTERS[@]}; do router="$router" bats labs/srlinux-01/tests/tests.bats; done
