name: test

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install bats
      run: sudo apt-get -y install bats

    - name: Run tests
      run: |
        export TERM=dumb
        router="srl01" bats labs/srlinux-01/tests/tests.bats
